# Generated by Django 5.2.3 on 2025-06-18 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubmission',
            old_name='error_message',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='task',
            name='expected_outputs',
        ),
        migrations.RemoveField(
            model_name='task',
            name='language',
        ),
        migrations.RemoveField(
            model_name='task',
            name='memory_limit',
        ),
        migrations.RemoveField(
            model_name='task',
            name='test_cases',
        ),
        migrations.AlterUniqueTogether(
            name='tasksubmission',
            unique_together={('student', 'task')},
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='time_taken',
            field=models.IntegerField(blank=True, help_text='Time taken in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='sample_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sample_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_limit',
            field=models.IntegerField(default=60, help_text='Time limit in minutes'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='language',
            field=models.CharField(default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='student', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='memory_used',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='submission_id',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='test_cases_passed',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='total_test_cases',
        ),
    ]
