# Generated by Django 5.2.3 on 2025-06-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('bca', 'BCA'), ('bsc_cs', 'B.Sc Computer Science'), ('bcom', 'B.Com'), ('ba', 'BA'), ('bba', 'BBA'), ('mca', 'MCA'), ('msc_cs', 'M.Sc Computer Science'), ('mba', 'MBA')], default='bca', max_length=20),
        ),
    ]
