# Generated by Django 5.2.3 on 2025-06-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('FS', 'Full Stack'), ('JAVA', 'JAVA'), ('PY', 'Python'), ('TEST', 'Testing'), ('CC', 'Cloud Computing'), ('AI', 'Artificial Intelligence')], default='bca', max_length=20),
        ),
    ]
